### PR TITLE
Added the ability to send ArtSync message in the Art-Net protocol implementation.

### PR DESCRIPTION
**Pull request by kacper516**
**Changes:**
- Implemented the send_artsync method, which sends an ArtSync message to Art-Net receiving devices.
- Added the artsync_header header to the StupidArtnet class for creating ArtSync messages.

**Purpose:**
Introducing the capability to send ArtSync messages enables synchronization of Art-Net receiving devices, which is essential for ensuring synchronized lighting effects on stage or in other environments.

## Summary by CodeRabbit

- **New Features**
    - Updated the StupidArtnet class to support creating and sending an ArtSync header, enhancing synchronization capabilities.

### CODE REVIEW

**Review by cpvalente — COMMENTED** [review]
Hi @kacper516 , thank you for this.

In your proposal, the user would have to imperatively emit the `ArtSync` packets while the `ArtDmx` packet sending is automated by the clock thread.

I wonder whether this process should be managed by the library rather than by the user. But I dont have experience in this matter.

Few suggestions:

Would it make sense that the internal automation sends the `ArtSync` packets?

Would we like to have an opt-in process for `ArtSync`, perhaps an option in the constructor?

From what I understand, `artDmx` packets are buffered until a sync command is shown, so we would need to keep the `ArtSync` at the desired refresh rate. Is this correct?

**Comment by kacper516** [comment]
In case we want to utilize ArtSync, we send it after **each buffer transmission** (sometimes we want to send a lot of buffers before artsync, what i tell about below).

For the ArtNet data transmission, we could consider adding an option to send ArtSync directly in the constructor. This way, we determine whether we will send synchronization data or not.

When setting up multiple ArtNet servers, for example, a list consisting of 20 ArtNet servers, each sending data to different universes but sequentially, I would like to synchronize the data only after iterating through all 20 elements. At that point, it constitutes one frame of animation for me. Then, we send the synchronization signal. For this purpose, I utilize a separate instance responsible for sending the buffer to a specific address.

Based on this, I'm introducing a commit that enables sending the synchronization signal after each packet transmission (by default, this option is set to false in the constructor). Additionally, I'm allowing direct invocation of the function via the class instance, as this might be useful in certain scenarios (at least in my case).

**Comment by cpvalente** [comment]
This all sounds sensible to me, thank you for your work.

I will prepare a release, meanwhile, do you think I could ask you for some feedback on this unresolved PR?
https://github.com/cpvalente/stupidArtnet/pull/25

**Review by cpvalente — APPROVED** [review]
Great work! Thank you for your help

**Pull request merged**
